#!/usr/bin/env python3
"""Generate the two-cabinet playtest entry from the shared expedition launcher."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]/'examples/arcade'
s=(root/'index.glyph').read_text()
s=s.replace('           :tower "assets/kenney/strips/tower-defense-kit.png" :fish "assets/kenney/strips/fish-kit.png"\n', '')
s=s.replace('           :grid "assets/kenney/strips/boardgame-kit.png"\n', '')
s=s.replace('Five worlds to explore. A new best line every time.','Two games. New routes. A better run is waiting.')
s=s.replace('(+ (:focus s) direction 5) 5','(+ (:focus s) direction 2) 2')
s=s.replace(')) 2\n', ')) 1\n').replace(')) -2 else', ')) -1 else')
for line in ['      (hit? 22 223 138 70) (open next 2)\n','      (hit? 170 223 138 70) (open next 3)\n','      (hit? 318 223 140 70) (open next 4)\n','      (hit? 334 323 124 24) (do (navigation/push "prototype-index.glyph") next)\n']:
 s=s.replace(line,'')
a=s.index('      (label "THE NEXT CABINETS')
b=s.index('      (label "Stick / arrows',a)
s=s[:a]+'''      (label "A SMALL EXPEDITION. ROOM TO MASTER IT." 22 224 11 "#f2cc85")
      (label "Three deliveries through gravity. One clean mountain descent." 22 248 12 "#94b1b7")
      (label "Earn medals. Save your best. Find another line." 22 272 12 "#94b1b7")
'''+s[b:]
s=s.replace('(label "Prototype archive >" 341 328 10 "#94b1b7")','(label "PLAYTEST / SECTOR 01" 341 328 9 "#94b1b7")')
(root/'demo.glyph').write_text('; Generated by tools/generate_demo.py from index.glyph.\n'+s)
